# Generated by Django 5.0.2 on 2024-03-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={},
        ),
    ]
